WITH B AS (
    SELECT 
        DISTINCT(PARENT_ID),
        COUNT(*) OVER (
            PARTITION BY PARENT_ID
        ) AS CHILD_COUNT
    FROM ECOLI_DATA
)

SELECT
    A.ID,
    IFNULL(B.CHILD_COUNT, 0) AS CHILD_COUNT
FROM ECOLI_DATA A
LEFT JOIN B ON A.ID = B.PARENT_ID
