SELECT
    T.ITEM_ID,
    B.ITEM_NAME,
    B.RARITY

FROM ITEM_TREE T
JOIN (
    SELECT ITEM_ID
    FROM ITEM_INFO
    WHERE RARITY = 'RARE'
) A
ON T.PARENT_ITEM_ID = A.ITEM_ID
LEFT JOIN (
    SELECT 
        ITEM_ID,
        ITEM_NAME,
        RARITY
    FROM ITEM_INFO
) B
ON T.ITEM_ID = B.ITEM_ID
ORDER BY T.ITEM_ID DESC;